/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-11-07 08:59:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class buylist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("	<title>::몬트라움:: 프리미엄 펫용품 전문쇼핑몰</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<style>\r\n");
      out.write("#popup-member-join-check { max-width: 540px; padding-top:50px;padding-bottom:30px;}\r\n");
      out.write("#popup-member-join-check .ws-join {text-align:center;border-bottom:1px solid #000;padding-bottom: 34px;margin-bottom: 26px; margin-top: 26px;}\r\n");
      out.write("#popup-member-join-check .ws-join .title {font-size:26px;}\r\n");
      out.write("#popup-member-join-check .ws-join .desc {font-size:13px; color:#555;}\r\n");
      out.write("#popup-member-join-check .ws-join .btn-ws-join {font-weight: 700;font-size: 15px;margin-top: 16px;border: none;display: inline-block;background-color: #000;color: #fff;padding: 16px 0px;width: 289px;}\r\n");
      out.write("\r\n");
      out.write("#popup-member-join-check .naver-join {text-align:center; margin-bottom: 26px;}\r\n");
      out.write("#popup-member-join-check .naver-join .title {font-size:26px;}\r\n");
      out.write("#popup-member-join-check .naver-join .desc {font-size:13px; color:#555;}\r\n");
      out.write("#popup-member-join-check .naver-join .btn-login-naver {font-weight: 700;font-size: 15px;margin-top: 16px;border: none;display: inline-block;background-color: #1EC800;color: #fff;padding: 16px 0px;width: 289px;background-image: url('../images/sns_logo_naver.png');background-position: 44px center;background-repeat: no-repeat;text-indent: 35px;}\r\n");
      out.write("#popup-member-join-check .naver-join .btn-login-facebook {font-weight: 700;font-size: 15px;margin-top: 16px;border: none;display: inline-block;background-color: #385898;color: #fff;padding: 16px 0px;width: 289px;background-image: url('../images/sns_logo_facebook.png');background-position: 44px center;background-repeat: no-repeat;text-indent: 35px;}\r\n");
      out.write("#popup-member-join-check .naver-join .btn-login-kakao {font-weight: 700;font-size: 15px;margin-top: 16px;border: none;display: inline-block;background-color: #F9DF33;color: #fff;padding: 16px 0px;width: 289px;background-image: url('../images/sns_logo_kakao.png');background-position: 44px center;background-repeat: no-repeat;text-indent: 35px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Google Tag Manager -->\r\n");
      out.write("<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\r\n");
      out.write("		new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\r\n");
      out.write("		j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\r\n");
      out.write("		'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\r\n");
      out.write("		})(window,document,'script','dataLayer','GTM-WDLJW3X');</script>\r\n");
      out.write("<!-- End Google Tag Manager -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--네이버 - 공통 스크립트-->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		var _NGUL = \"wcs.naver.net/wcslog.js\";\r\n");
      out.write("		var _NPR = location.protocol==\"https:\"?\"https://\"+_NGUL:\"http://\"+_NGUL;\r\n");
      out.write("		document.writeln(\"<scr\"+\"ipt type='text/ja\"+\"vascript' src='\"+ _NPR +\"'></scr\"+\"ipt>\");\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 네이버 - 공통 적용 스크립트 , 모든 페이지에 노출되도록 설치. 단 전환페이지 설정값보다 항상 하단에 위치해야함 --> \r\n");
      out.write("	<script type=\"text/javascript\"> \r\n");
      out.write("		if (!wcs_add) var wcs_add={};\r\n");
      out.write("		wcs_add[\"wa\"] = \"s_38867da41604\";\r\n");
      out.write("		if (!_nasa) var _nasa={};\r\n");
      out.write("		wcs.inflow();\r\n");
      out.write("		wcs_do(_nasa);\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 스크립트 추가 요청 18.05.03 목 -->\r\n");
      out.write("	<!-- Global site tag (gtag.js) - AdWords: 808804844 -->\r\n");
      out.write("	<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-174911447-1\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	window.dataLayer = window.dataLayer || [];\r\n");
      out.write("	function gtag(){dataLayer.push(arguments);}\r\n");
      out.write("	gtag('js', new Date());\r\n");
      out.write("	//gtag('config', 'AW-808804844');\r\n");
      out.write("	gtag('config', 'UA-174911447-1');\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Facebook Pixel Code -->\r\n");
      out.write("	<script>\r\n");
      out.write("	!function(f,b,e,v,n,t,s)\r\n");
      out.write("	{if(f.fbq)return;n=f.fbq=function(){n.callMethod?\r\n");
      out.write("	n.callMethod.apply(n,arguments):n.queue.push(arguments)};\r\n");
      out.write("	if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';\r\n");
      out.write("	n.queue=[];t=b.createElement(e);t.async=!0;\r\n");
      out.write("	t.src=v;s=b.getElementsByTagName(e)[0];\r\n");
      out.write("	s.parentNode.insertBefore(t,s)}(window,document,'script',\r\n");
      out.write("	'https://connect.facebook.net/en_US/fbevents.js');\r\n");
      out.write("	fbq('init', '470967463719666'); \r\n");
      out.write("	fbq('track', 'PageView');\r\n");
      out.write("	</script>\r\n");
      out.write("	<noscript>\r\n");
      out.write("		<img height=\"1\" width=\"1\" src=\"https://www.facebook.com/tr?id=470967463719666&ev=PageView&noscript=1\"/>\r\n");
      out.write("	</noscript>\r\n");
      out.write("	<!-- End Facebook Pixel Code -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 카카오(방문) 2019-10-17 -->\r\n");
      out.write("	<script type=\"text/javascript\" charset=\"UTF-8\" src=\"//t1.daumcdn.net/adfit/static/kp.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		kakaoPixel('2880532030433936382').pageView();\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- 카카오(방문) 2019-10-17 -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Start Taggers Pixel -->\r\n");
      out.write("	<script>!function(t,e,n){t[n]=t[n]||[],t[n].push({\"gtm.start\":(new Date).getTime(),event:\"gtm.js\"})}(window,document,\"dataLayer\")</script><script async src=\"https://www.googletagmanager.com/gtm.js?l=dataLayer&id=GTM-N6PTCN3\"></script>\r\n");
      out.write("	<script async src=\"https://www.googletagmanager.com/gtag/js\"></script>\r\n");
      out.write("	<script async src=\"https://www.google-analytics.com/analytics.js\"></script>\r\n");
      out.write("	<script async src=\"https://www.googleadservices.com/pagead/conversion_async.js\"></script>\r\n");
      out.write("	<script>!function(e,u){e.fbq||(u=e.fbq=function(){u.callMethod?u.callMethod.apply(u,arguments):u.queue.push(arguments)},e._fbq||(e._fbq=u),(u.push=u).loaded=!0,u.version=\"2.0\",u.queue=[])}(window)</script><script async src=\"https://connect.facebook.net/en_US/fbevents.js\"></script>\r\n");
      out.write("	<!-- End Taggers Pixel -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> -->\r\n");
      out.write("<!-- ############################################## Script Include #################################################### -->\r\n");
      out.write("<!-- ################################################################################################################## -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"mobile-wrapper\">\r\n");
      out.write("	<!--헤더영역시작-->\r\n");
      out.write("	\r\n");
      out.write("	<!--헤더영역종료-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--네비영역시작-->\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	<!--네비영역종료-->\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("	httpUrl = \"/common/process/buy_list.asp\"\r\n");
      out.write("	httpUrl2 = \"www.montraum.com\"\r\n");
      out.write("\r\n");
      out.write("	function loginCheck() {\r\n");
      out.write("		location.href=\"/common/all_site/member/login.asp?refer_page=%2Fcommon%2Fprocess%2Fbuy%5Flist%2Easp\"\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"javascript\" src=\"/top.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"/_vir0001/code.js\" charset=\"euc-kr\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--Content영역시작-->\r\n");
      out.write("		<section>\r\n");
      out.write("			<div id=\"page-member-order-list\" class=\"section-member pc-width\">\r\n");
      out.write("				<div id=\"navigation-bar\"><script>document.write(navistr)</script></div>\r\n");
      out.write("				<h2 class=\"page-title\"><script>document.write(siteTitle)</script></h2>\r\n");
      out.write("				\r\n");
      out.write("	<div class=\"member-nav-wrapper\">\r\n");
      out.write("	<ul class=\"member-nav open-sub-menu\"> <!-- 나의 쇼핑현황일 때 open-sub-menu class를 추가 -->\r\n");
      out.write("		<li class=\"active\">\r\n");
      out.write("			<a href=\"/common/process/buy_list.asp\">나의 쇼핑현황</a>\r\n");
      out.write("			<div class=\"member-sub-nav\">\r\n");
      out.write("				<a href=\"/common/process/buy_list.asp\" class=\"active\">주문내역</a>\r\n");
      out.write("				<a href=\"/common/process/order_list.asp?iniCategory=0\">장바구니</a>\r\n");
      out.write("				<a href=\"/common/process/wish_list.asp\">위시리스트</a>\r\n");
      out.write("				<a href=\"/common/process/mycoupon.asp\">쿠폰</a>\r\n");
      out.write("				<a href=\"/common/process/mypoint.asp\">예치금</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li><a href=\"/common/all_site/member/member_edit.asp\">개인정보수정</a></li>\r\n");
      out.write("		<li><a href=\"/common/process/baesong_addr.asp\">주소록관리</a></li>\r\n");
      out.write("		<li class=\"hide-mobile\"><a href=\"/common/process/qanda/list.asp\">1:1문의</a></li>\r\n");
      out.write("		<li><a href=\"/common/process/productAfter/myreview_view.asp\">나의후기</a></li>\r\n");
      out.write("		<li><a href=\"/common/all_site/member/member_out.asp\">회원탈퇴</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"top-summary\">\r\n");
      out.write("		<p class=\"welcome-member\"> name 고객님, 환영합니다.</p>\r\n");
      out.write("		<div class=\"top-infobox2 my-membership\">\r\n");
      out.write("			<div class=\"level-box\">\r\n");
      out.write("        <div class=\"level-blt\"><img src=\"/static/img/member/blt2_membership_1.png\"/></div>\r\n");
      out.write("        <div class=\"level-info\">\r\n");
      out.write("          <div class=\"title-name only-pc\">11월 회원등급</div>\r\n");
      out.write("          <div class=\"title-name only-mobile\">11월<br/>회원등급</div>\r\n");
      out.write("          <div class=\"level-name only-pc\" style=\"width:200px;\">신규 펫팸<br/><span class=\"membership-view\" style=\"padding: 4px 7px;background: #000;\"><a href=\"/about/members.asp\" style=\"color: #fff;font-weight: bold;text-decoration: none;\">회원혜택 확인 및 쿠폰다운로드</a></span></div>\r\n");
      out.write("          <div class=\"level-name only-mobile\">신규 펫팸<div class=\"level-date only-mobile\">21.4.26 ~ 21.10.25</div>\r\n");
      out.write("          <br/><span class=\"membership-view\" style=\"padding: 4px 7px;background: #000;\"><a href=\"/about/members.asp\" style=\"color: #fff;font-weight: bold;\">회원혜택 확인 및 쿠폰다운로드</a></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"level-date only-pc\">＊등급산정기간 - 2021.4.26 ~ 2021.10.25</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"level-box2\">\r\n");
      out.write("        <div class=\"order-buy-info only-pc\"><span class=\"highlight\">최근 6개월간 주문금액 <span style='color:#c00000;font-weight:bold;'>0</span>원</span></div>\r\n");
      out.write("        <div class=\"order-buy-info only-mobile\"><span class=\"highlight\">최근 6개월간 주문금액 <span style='color:#c00000;font-weight:bold;'>0</span>원</span></div>\r\n");
      out.write("        <div class=\"amount-info only-pc\"><span class=\"highlight\">[<span style='color:#ae8346;font-weight:bold;'>일반 펫팸</span>]까지 <span style='color:#c00000;font-weight:bold;'>1</span>회 구매 남았습니다.</span></div>\r\n");
      out.write("        <div class=\"amount-info only-mobile\"><span class=\"highlight\">[<span style='color:#ae8346;font-weight:bold;'>일반 펫팸</span>]까지 <span style='color:#c00000;font-weight:bold;'>1</span>회 구매 남았습니다.</span></div>\r\n");
      out.write("        <div class=\"diff-info only-pc\">*등급산정 기준에 따른 예상 금액으로 총주문금액과 다를 수 있습니다.</div>\r\n");
      out.write("        <div class=\"diff-info only-mobile\">등급산정 기준에 따른 예상금액으로 총주문금액과 다를 수 있습니다.</div>\r\n");
      out.write("      </div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"top-infobox3\" style=\"text-align: center\">\r\n");
      out.write("			<div class=\"my-infobox my-balance2 my-info\">\r\n");
      out.write("			  <img class=\"only-pc\" src=\"/static/img/member/balance.png\" style=\"float: left;margin-top: -11px;\">\r\n");
      out.write("			  <img class=\"only-mobile\" src=\"/static/img/member/balance.png\" style=\"float: left;width: 35px;\">\r\n");
      out.write("				<div class=\"name only-pc\" style=\"float: left;padding: 25px 10px;font-size: 15px;\">예치금<br/><a href=\"/common/process/mypoint.asp\">0</a> 원</div>\r\n");
      out.write("				<div class=\"name only-mobile\" style=\"float: left;\">예치금<br/><a href=\"/common/process/mypoint.asp\">0</a> 원</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"my-infobox my-coupon2 my-info\">\r\n");
      out.write("        <img class=\"only-pc\" src=\"/static/img/member/coupon.png\" style=\"float: left;\">\r\n");
      out.write("        <img class=\"only-mobile\" src=\"/static/img/member/coupon.png\" style=\"float: left;width: 35px;\">\r\n");
      out.write("        <div class=\"name only-pc\" style=\"float: left;padding: 25px 10px;font-size: 15px;\">쿠폰<br/><a href=\"/common/process/mycoupon.asp\">0</a> 장</div>\r\n");
      out.write("        <div class=\"name only-mobile\" style=\"float: left;\">쿠폰<br/><a href=\"/common/process/mycoupon.asp\">0</a> 장</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"my-infobox my-wish2 my-info\">\r\n");
      out.write("			  <img class=\"only-pc\" src=\"/static/img/member/wish.png\" style=\"float: left;\">\r\n");
      out.write("			  <img class=\"only-mobile\" src=\"/static/img/member/wish.png\" style=\"float: left;width: 35px;\">\r\n");
      out.write("				<div class=\"name only-pc\" style=\"float: left;padding: 25px 10px;font-size: 15px;\">위시리스트<br/><a href=\"/common/process/wish_list.asp\">0</a> 개</div>\r\n");
      out.write("				<div class=\"name only-mobile\" style=\"float: left;\">위시리스트<br/><a href=\"/common/process/wish_list.asp\">0</a> 개</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"my-infobox my-cart2 my-info\">\r\n");
      out.write("			  <img class=\"only-pc\" src=\"/static/img/member/cart.png\" style=\"float: left;margin-top: -5px;\">\r\n");
      out.write("			  <img class=\"only-mobile\" src=\"/static/img/member/cart.png\" style=\"float: left;width: 35px;\">\r\n");
      out.write("        <div class=\"name only-pc\" style=\"float: left;padding: 25px 10px;font-size: 15px;\">장바구니<br/><a href=\"/common/process/order_list.asp?iniCategory=0\">0</a> 개</div>\r\n");
      out.write("        <div class=\"name only-mobile\" style=\"float: left;\">장바구니<br/><a href=\"/common/process/order_list.asp?iniCategory=0\">0</a> 개</div>\r\n");
      out.write("      </div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"contents-wrapper item-list\" id=\"item-list\">\r\n");
      out.write("					<h3 class=\"sub-title\">주문내역</h3>\r\n");
      out.write("					<span class=\"only-pc\">고객님께서 주문하신 정보와 제품의 배송여부를 조회하실 수 있습니다.</span>\r\n");
      out.write("          <span class=\"only-mobile\">주문하신 정보와 제품의 배송여부를 조회</span>\r\n");
      out.write("          <div class=\"page-content-desc only-pc\">\r\n");
      out.write("            <span class=\"btn-write btn-up-right\" id=\"searchDate3\" name=\"searchDate3\" onclick=\"location.href='buy_list.asp?searchDate=3';\" style=\"right:215px;\">최근3개월</span>\r\n");
      out.write("            <span class=\"btn-write btn-up-right\" id=\"searchDate6\" name=\"searchDate6\" onclick=\"location.href='buy_list.asp?searchDate=6';\" style=\"right:100px;\">최근6개월</span>\r\n");
      out.write("            <span class=\"btn-write btn-up-right\" id=\"searchDate12\" name=\"searchDate12\" onclick=\"location.href='buy_list.asp?searchDate=12';\">최근1년</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"page-content-desc only-mobile\">\r\n");
      out.write("            <span class=\"btn-write btn-up-right\" id=\"searchDate3\" name=\"searchDate3\" onclick=\"location.href='buy_list.asp?searchDate=3';\" style=\"right:152px;top:-60px;\">최근3개월</span>\r\n");
      out.write("            <span class=\"btn-write btn-up-right\" id=\"searchDate6\" name=\"searchDate6\" onclick=\"location.href='buy_list.asp?searchDate=6';\" style=\"right:70px;top:-60px;\">최근6개월</span>\r\n");
      out.write("            <span class=\"btn-write btn-up-right\" id=\"searchDate12\" name=\"searchDate12\" onclick=\"location.href='buy_list.asp?searchDate=12';\" style=\"top:-60px;\">최근1년</span>\r\n");
      out.write("          </div>\r\n");
      out.write("			\r\n");
      out.write("					<div class=\"only-pc\">\r\n");
      out.write("					<table class=\"item-table type1\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th class=\"item-info\">주문일시</th>\r\n");
      out.write("							<th class=\"order-no\">주문번호</th>\r\n");
      out.write("							<th class=\"count\">결제방법</th>\r\n");
      out.write("							<th class=\"ship-status\">주문금액</th>\r\n");
      out.write("							<th class=\"action\">주문상태</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<!--내용이 없을때 사용해주세요\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"5\">주문하신 내역이 없습니다.</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						-->\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"5\" class=\"empty\">주문하신 내역이 없습니다.</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("					</table>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"only-mobile\">\r\n");
      out.write("					<table class=\"item-table type1\">\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"2\" class=\"empty\">주문하신 내역이 없습니다.</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("					</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- PC 페이지 -->\r\n");
      out.write("					<div class=\"pagination1 only-pc\">\r\n");
      out.write("					<span class='btn-page prev'></span><span class='btn-page next'></span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 모바일 페이지 -->\r\n");
      out.write("					<div class=\"pagination2 only-mobile\">\r\n");
      out.write("						<span class='btn-page prev'></span><span class='btn-page next'></span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"notice-wrapper clearfix\">\r\n");
      out.write("						<h3>확인해주세요</h3>\r\n");
      out.write("						<ul class=\"notice-list\">\r\n");
      out.write("							<li>최근 3개월 동안의 주문현황 조회가 가능합니다.</li>\r\n");
      out.write("							<li>주문번호를 클릭하시면 주문 상세내역을 확인하실 수 있습니다.</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("<!--Content영역종료-->\r\n");
      out.write("<div style=\"display:none;\">\r\n");
      out.write("	<!--풋터영역시작-->\r\n");
      out.write("</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
