/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-11-08 07:32:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>login</title>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("	httpUrl = \"login.html\"\r\n");
      out.write("	httpUrl2 = \"www.montraum.com\"\r\n");
      out.write("\r\n");
      out.write("	function loginCheck() {\r\n");
      out.write("		location.href=\"login6d1f.html?refer_page=%2Fcommon%2Fall%5Fsite%2Fmember%2Flogin%2Easp\"\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 페이지 로그인 부분 관리  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/top.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#page-member-login form{margin-left:0px;}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 페이지 로그인 부분 관리  end -->\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<div id=\"page-member-login\" class=\"section-member pc-width\">\r\n");
      out.write("	<div id=\"navigation-bar\"><script>document.write(navistr)</script></div>\r\n");
      out.write("	<h2 class=\"page-title\"><script>document.write(siteTitle)</script></h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"contents-wrapper login-line\">\r\n");
      out.write("		<div class=\"tab-contents\">\r\n");
      out.write("			<div class=\"tab-header\">\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tab-content\">\r\n");
      out.write("				<!-- 회원 로그인 -->\r\n");
      out.write("				<div class=\"content1 active\">\r\n");
      out.write("					<form name=\"mainFrm\" method=\"post\" action=\"https://www.montraum.com/common/all_site/member/login_process.asp\">\r\n");
      out.write("					<input type=\"hidden\" name=\"refer_page\" value=\"\">					\r\n");
      out.write("					<div class=\"clearfix\">\r\n");
      out.write("						<ul class=\"input-items\">\r\n");
      out.write("							<li>\r\n");
      out.write("								<span class=\"input-name\">아이디</span>\r\n");
      out.write("								<input type=\"text\" class=\"input1\" name=\"LoginId\" onKeyDown=\"javascript:acceptEnter12();\" />\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<span class=\"input-name\">비밀번호</span>\r\n");
      out.write("								<input type=\"password\" class=\"input1\" name=\"LoginPwd\" onKeyDown=\"javascript:acceptEnter22()\" />\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<div class=\"btn-wrapper\">\r\n");
      out.write("							<input type=\"button\" class=\"btn-login\" value=\"LOGIN\" onclick=\"javascript:SendLoginMain();\" style=\"cursor:pointer;\" />\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</form>						\r\n");
      out.write("					<div class=\"page-link\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"searchidinfo2ce3.html?ProcessGubun=A\">아이디 찾기</a></li>\r\n");
      out.write("							<li><a href=\"searchidinfo0a92.html?ProcessGubun=B\">비밀번호 찾기</a></li>\r\n");
      out.write("							<li><a href=\"join_write.jsp\">회원가입</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"contents-wrapper member-ship-guide clearfix\">\r\n");
      out.write("	<div class=\"intro\">\r\n");
      out.write("		<p class=\"txt-membership\">MEMBERSHIP</p>\r\n");
      out.write("		<p class=\"txt-program\">PROGRAM</p>\r\n");
      out.write("		<p class=\"txt-desc\">몬트라움 회원만을 위한 차별화된 혜택을 경험하세요.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<ul class=\"benefits\">\r\n");
      out.write("		<li class=\"b-coupon\">\r\n");
      out.write("			<p class=\"text1\">신규회원</p>\r\n");
      out.write("			<p class=\"text2\">할인쿠폰 지급</p>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li class=\"b-level\">\r\n");
      out.write("			<p class=\"text1\">1회 구매 후</p>\r\n");
      out.write("			<p class=\"text2\">바로 등급 UP</p>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li class=\"b-event\">\r\n");
      out.write("			<p class=\"text1\">다양한</p>\r\n");
      out.write("			<p class=\"text2\">이벤트 참여</p>\r\n");
      out.write("		</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--풋터영역시작 footer 건들지 않는다 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function acceptEnter12() {\r\n");
      out.write("		if (event.keyCode == 13) {\r\n");
      out.write("			document.mainFrm.LoginPwd.focus();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function acceptEnter22() {\r\n");
      out.write("		if (event.keyCode == 13) {\r\n");
      out.write("			SendLoginMain();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//메인 로그인 하는 부분\r\n");
      out.write("	function SendLoginMain() {\r\n");
      out.write("		var frm = document.mainFrm;\r\n");
      out.write("\r\n");
      out.write("		if (isEmpty(frm.LoginId.value)) {\r\n");
      out.write("			alert(\"ID를 입력해 주십시오.\");\r\n");
      out.write("			frm.LoginId.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (isEmpty(frm.LoginPwd.value)) {\r\n");
      out.write("			alert(\"비밀번호를 입력해 주십시오.\");\r\n");
      out.write("			frm.LoginPwd.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		frm.submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
