/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-11-08 02:48:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fModify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("	<title>정보수정/title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--네비영역종료-->\r\n");
      out.write("\r\n");
      out.write("	<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"../resources/js/top.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"../resources/js/code.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"../resources/js/code_member.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("	//영문/숫자 체크\r\n");
      out.write("	function check_Alpha_Num(input){\r\n");
      out.write("		var err_cnt=0\r\n");
      out.write("		for (var i = 0; i < input.length; i++) {\r\n");
      out.write("			var val = input.charAt(i);\r\n");
      out.write("			if (!((val >= \"0\" && val <= \"9\") || (val >= \"a\" && val <= \"z\") || (val >= \"A\" && val <= \"Z\")))\r\n");
      out.write("			err_cnt ++\r\n");
      out.write("		}\r\n");
      out.write("		if (err_cnt == 0 ) return true;\r\n");
      out.write("		else return false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//숫자체크(연락처, 휴대폰번호)\r\n");
      out.write("	function onlyNumber() {\r\n");
      out.write("		if (event.keyCode!=13 && ((event.keyCode < 48) || (event.keyCode > 57))){\r\n");
      out.write("			event.returnValue = false;\r\n");
      out.write("			alert('숫자만 입력하세요.');\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//아이디 중복확인 popup 호출\r\n");
      out.write("	function idchk(){\r\n");
      out.write("		var id = document.frmReg.id.value;\r\n");
      out.write("		if( id.length < 6 || id.length > 15 ) {\r\n");
      out.write("			alert(\"아이디를 입력하세요. (6-15자).\");\r\n");
      out.write("			document.frmReg.id.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if (! check_Alpha_Num(id.toUpperCase()))	{\r\n");
      out.write("			alert(\"아이디는 영문/숫자 이외의 문자는 허용되지 않습니다. \");\r\n");
      out.write("			document.frmReg.id.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		window.open(\"/common/all_site/member/findid.asp?UserId=\" + id,\"아이디중복검사\",\"width=450,height=320,top=100,left=100,scrollbars=no,resizable=no\");\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//Submit\r\n");
      out.write("	function WriteCheck2(){\r\n");
      out.write("		var Frm = document.frmReg;\r\n");
      out.write("	\r\n");
      out.write("		if (\"아이디\" ==  \"\"){\r\n");
      out.write("			// id check 시작\r\n");
      out.write("			if (isEmpty(Frm.id.value)){	alert(\"ID를 입력해 주십시오\");  Frm.id.focus(); return}\r\n");
      out.write("			if (Frm.id.value.length < 6 || Frm.id.value.length > 15 ){	alert(\"아이디는 6자이상 15이하로 입력하셔야 합니다\");  Frm.id.focus(); return}\r\n");
      out.write("			for(i=0;i<Frm.id.value.length;i++) {\r\n");
      out.write("			var a=Frm.id.value.charCodeAt(i);\r\n");
      out.write("				if (a > 128) {	alert(\"ID 로 한글은 사용하실수 없습니다.\");		Frm.id.value=\"\";	Frm.id.focus();		return;	}\r\n");
      out.write("			}\r\n");
      out.write("			if (!(check_Alpha_Num(Frm.id.value))) {	alert(\"ID는 반드시 영문과 숫자 조합으로 등록하셔야 합니다.\");	Frm.id.focus();		return	}\r\n");
      out.write("			if (Frm.idcheck_ok.value != \"ok\"){alert(\"ID 중복확인을 하세요.\"); return;}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 비밀번호 check\r\n");
      out.write("		var cnt = 0;\r\n");
      out.write("		var str = Frm.pwd1.value;\r\n");
      out.write("		for( var i=0; i < str.length; ++i)\r\n");
      out.write("		{\r\n");
      out.write("			if( str.charAt(0) == str.substring( i, i+1 ) ) ++cnt;\r\n");
      out.write("		}		\r\n");
      out.write("		if (Frm.pwd1.value != \"\"){ \r\n");
      out.write("			if( cnt == str.length ) {\r\n");
      out.write("				alert(\"보안상의 이유로 한 문자로 연속된 비밀번호는 허용하지 않습니다.\");\r\n");
      out.write("				Frm.pwd1.value=\"\";\r\n");
      out.write("				Frm.pwd2.value=\"\";\r\n");
      out.write("				Frm.pwd2_mobile.value=\"\";\r\n");
      out.write("				Frm.pwd1.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (isEmpty(Frm.pwd1.value)){ alert(\"비밀번호를 입력해 주십시오\");  Frm.pwd1.focus(); return}\r\n");
      out.write("		if (isEmpty(Frm.pwd2.value)&&isEmpty(Frm.pwd2_mobile.value)){ alert(\"비밀번호 확인을 입력해 주십시오\");  Frm.pwd2.focus(); return}\r\n");
      out.write("		if (Frm.pwd2.value != \"\" && Frm.pwd1.value != Frm.pwd2.value ){\r\n");
      out.write("			alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("			Frm.pwd1.value=\"\";\r\n");
      out.write("			Frm.pwd2.value=\"\";\r\n");
      out.write("			Frm.pwd1.focus();\r\n");
      out.write("			return\r\n");
      out.write("		}\r\n");
      out.write("		if (Frm.pwd2_mobile.value != \"\" && Frm.pwd1.value != Frm.pwd2_mobile.value ){\r\n");
      out.write("			alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("			Frm.pwd1.value=\"\";\r\n");
      out.write("			Frm.pwd2_mobile.value=\"\";\r\n");
      out.write("			Frm.pwd1.focus();\r\n");
      out.write("			return\r\n");
      out.write("		}\r\n");
      out.write("		if (Frm.pwd1.value.length < 6 || Frm.pwd1.value.length > 15 ){	alert(\"비밀번호는 6자이상 15이하로 입력하셔야 합니다\");  Frm.pwd1.focus(); return}\r\n");
      out.write("		if (!(check_Alpha_Num(Frm.pwd1.value) == true )) {	alert(\"비밀번호는 반드시 영문과 숫자 조합으로 등록하셔야 합니다.\");	Frm.pwd1.focus();	return	}\r\n");
      out.write("\r\n");
      out.write("		//email 새로들어가는 부분 시작\r\n");
      out.write("		if (isEmpty(Frm.email.value)){ alert(\"이메일 주소 앞자리를 입력해 주십시오\");  Frm.email.focus(); return}\r\n");
      out.write("		if (isEmpty(Frm.email2.value)){ alert(\"이메일 주소 뒷부분을 입력 또는 선택해 주십시오\");  Frm.SelectEmail.focus(); return}\r\n");
      out.write("\r\n");
      out.write("		//핸드폰번호\r\n");
      out.write("		if (isEmpty(Frm.mobile1.value)){ alert(\"핸드폰 번호 앞자리를 선택해 주십시오\");  Frm.mobile1.focus(); return}\r\n");
      out.write("		if (isEmpty(Frm.mobile2.value)){ alert(\"핸드폰 번호 가운데자리를 입력해 주십시오\");  Frm.mobile2.focus(); return}\r\n");
      out.write("		if (isEmpty(Frm.mobile3.value)){ alert(\"핸드폰 번호 뒷자리를 입력해 주십시오\");  Frm.mobile3.focus(); return}\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("		//우편번호 주소\r\n");
      out.write("		if (isEmpty(Frm.zip.value)){ alert(\"우편번호를 입력해 주십시오\");  Frm.zip.focus(); return}\r\n");
      out.write("		if (isEmpty(Frm.addr1.value)){ alert(\"주소를 입력해 주십시오\");  Frm.addr1.focus(); return}\r\n");
      out.write("		if (isEmpty(Frm.addr2.value)){ alert(\"나머지 주소를 입력해 주십시오\");  Frm.addr2.focus(); return}\r\n");
      out.write("*/\r\n");
      out.write("		if(mobileChk()){\r\n");
      out.write("			Frm.action = \"member_edit_DB.asp\";\r\n");
      out.write("			Frm.target = \"_self\";\r\n");
      out.write("			Frm.submit();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//메일주소 선택\r\n");
      out.write("	function ChangeEmail()\r\n");
      out.write("	{\r\n");
      out.write("		if (document.getElementsByName(\"SelectEmail\")[0].value == \"\")\r\n");
      out.write("		{\r\n");
      out.write("			document.getElementsByName(\"email2\")[0].readOnly = false;\r\n");
      out.write("			document.getElementsByName(\"email2\")[0].value = \"\";\r\n");
      out.write("			document.getElementsByName(\"email2\")[0].style.backgroundColor = \"#ffffff\";\r\n");
      out.write("    	    document.getElementsByName(\"email2\")[0].style.color = \"#000000\";\r\n");
      out.write("\r\n");
      out.write("		}else{\r\n");
      out.write("			document.getElementsByName(\"email2\")[0].readOnly = true;\r\n");
      out.write("			document.getElementsByName(\"email2\")[0].value = document.getElementsByName(\"SelectEmail\")[0].value ;\r\n");
      out.write("			document.getElementsByName(\"email2\")[0].style.backgroundColor = \"#EEEEEE\";\r\n");
      out.write("    	    document.getElementsByName(\"email2\")[0].style.color = \"#555555\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//기념일,아이정보\r\n");
      out.write("	function fn_ymd(name){\r\n");
      out.write("\r\n");
      out.write("		rValue = new Array()\r\n");
      out.write("		if(name == \"Marry\"){\r\n");
      out.write("			field_name2 = name+\"Month\"\r\n");
      out.write("			field_name3 = name+\"Day\"\r\n");
      out.write("		}else{\r\n");
      out.write("			field_name1 = \"baby\"+name+\"_birth_1\"\r\n");
      out.write("			field_name2 = \"baby\"+name+\"_birth_2\"\r\n");
      out.write("			field_name3 = \"baby\"+name+\"_birth_3\"\r\n");
      out.write("\r\n");
      out.write("			//년도\r\n");
      out.write("			rValue.push('<select name=\"'+ field_name1 +'\">')\r\n");
      out.write("			rValue.push('<option value=\"\">선택</option>')\r\n");
      out.write("			d = new Date\r\n");
      out.write("			nowYear = d.getFullYear()+1;\r\n");
      out.write("			for (i=1995; i <= nowYear ; i++){\r\n");
      out.write("				rValue.push('<option value=\"'+i+'\">'+i+'</option>')\r\n");
      out.write("			}\r\n");
      out.write("			rValue.push('</select> 년 ')\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		//월\r\n");
      out.write("		rValue.push('<select name=\"'+ field_name2 +'\">')\r\n");
      out.write("		rValue.push('<option value=\"\">선택</option>')\r\n");
      out.write("		for (i=1; i <= 12 ; i++){\r\n");
      out.write("			val_month = select_zero(i,2)\r\n");
      out.write("			rValue.push('<option value=\"'+val_month+'\">'+val_month+'</option>')\r\n");
      out.write("		}\r\n");
      out.write("		rValue.push('</select> 월 ')\r\n");
      out.write("\r\n");
      out.write("		//일\r\n");
      out.write("		rValue.push('<select name=\"'+ field_name3 +'\">')\r\n");
      out.write("		rValue.push('<option value=\"\">선택</option>')\r\n");
      out.write("		for (i=1; i <= 31 ; i++){\r\n");
      out.write("			val_day = select_zero(i,2)\r\n");
      out.write("			rValue.push('<option value=\"'+val_day+'\">'+val_day+'</option>')\r\n");
      out.write("		}\r\n");
      out.write("		rValue.push('</select> 일')\r\n");
      out.write("		document.writeln (rValue.join(\"\"))\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//이메일 주소 체크 정규식 - 20130409\r\n");
      out.write("	function EmailCheck(mail) {\r\n");
      out.write("		var sMail = /^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/; \r\n");
      out.write("		if(sMail.test(mail)===false) {return false;}else{return true;}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function nextCodeFnc(chk) {\r\n");
      out.write("		//체크박스 단일선택\r\n");
      out.write("		var obj = document.getElementsByName(\"exYear\");\r\n");
      out.write("		for(var i=0; i<obj.length; i++){\r\n");
      out.write("			if(obj[i].value != chk){\r\n");
      out.write("				obj[i].checked = false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("//-->\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<!--Content영역시작-->\r\n");
      out.write("<section>\r\n");
      out.write("	<div id=\"page-member-info\" class=\"section-member pc-width\">\r\n");
      out.write("		<div id=\"navigation-bar\"><script>document.write(navistr)</script></div>\r\n");
      out.write("		<h2 class=\"page-title\"><script>document.write(siteTitle)</script></h2>\r\n");
      out.write("		<!-- mypage 상단 시작 -->\r\n");
      out.write("		\r\n");
      out.write("	<div class=\"member-nav-wrapper\">\r\n");
      out.write("	<ul class=\"member-nav\"> <!-- 나의 쇼핑현황일 때 open-sub-menu class를 추가 -->\r\n");
      out.write("		<li>\r\n");
      out.write("			<a href=\"orderlist.jsp\">나의 쇼핑현황</a>\r\n");
      out.write("			<div class=\"member-sub-nav\">\r\n");
      out.write("				<a href=\"orderlist.jsp\">주문내역</a>\r\n");
      out.write("				<a href=\"shoppingbasket.jsp\">장바구니</a>\r\n");
      out.write("				<a href=\"wish.jsp\">위시리스트</a>\r\n");
      out.write("				<a href=\"mycoupon.jsp\">쿠폰</a>\r\n");
      out.write("				<a href=\"mypoint.jsp\">예치금</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li class=\"active\"><a href=\"member_Modify.jsp\">개인정보수정</a></li>\r\n");
      out.write("\r\n");
      out.write("		<li class=\"hide-mobile\"><a href=\"qna.jsp\">1:1문의</a></li>\r\n");
      out.write("		<li><a href=\"myreview_view.jsp\">나의후기</a></li>\r\n");
      out.write("		<li><a href=\"member_Withdrawal.jsp\">회원탈퇴</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<!-- mypage 상단 끝 -->\r\n");
      out.write("		<form name=\"frmReg\" action=\"/common/all_site/member/member_edit_DB.asp\" method=\"post\">\r\n");
      out.write("		<input type=\"hidden\" name=\"EditGubun\" value=\"M\">\r\n");
      out.write("		<input type=\"hidden\" name =\"Mobile_Ori\" value=\"\">\r\n");
      out.write("		<input type=\"hidden\" name =\"Email_Ori\" value=\"\">\r\n");
      out.write("		<input type=\"hidden\" name=\"certNum\" value=\"\">\r\n");
      out.write("		<input type=\"hidden\" name=\"mobileCert_ok\" value=\"\">\r\n");
      out.write("		<div class=\"contents-wrapper member-info-form\">\r\n");
      out.write("			<h2 class=\"page-sub-title kr\">개인정보 수정</h2>\r\n");
      out.write("			<div class=\"page-content-desc\">\r\n");
      out.write("				고객님의 소중한 정보를 관리하세요.\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<h3 class=\"block-title\">필수정보</h3>\r\n");
      out.write("			\r\n");
      out.write("			<table class=\"item-table type1 input-form\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>아이디</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div id=\"user_id\" name=\"user_id\"></div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호</th>\r\n");
      out.write("					<td> \r\n");
      out.write("						<input type=\"password\" name=\"pwd1\" maxlength=\"20\" class=\"input1\" />\r\n");
      out.write("						<span class=\"password-check\">\r\n");
      out.write("							비밀번호 확인 \r\n");
      out.write("							<input type=\"password\" name=\"pwd2\" maxlength=\"20\" class=\"input1\" />\r\n");
      out.write("						</span>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"password-check-mobile\">\r\n");
      out.write("					<th>비밀번호 확인</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"password\" name=\"pwd2_mobile\" maxlength=\"20\" class=\"input1\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이름</th>\r\n");
      out.write("					<td><div id=\"user_name\" name=\"user_name\"></div>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이메일</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"email\" maxlength=\"45\" onkeydown=\"space_no()\" onkeyup=\"space_no2()\" autocomplete=\"off\" class=\"input1 email1\" /> @\r\n");
      out.write("						<input type=\"text\" name=\"email2\"  maxlength=\"30\" onkeydown =\"space_no()\" onkeyup=\"space_no2()\" class=\"input1 email2\" />\r\n");
      out.write("						<select name=\"SelectEmail\" OnChange=\"ChangeEmail()\" class=\"type1 email-select\">\r\n");
      out.write("							<script type=\"javascript\">make_select_code(\"select\",\"email\",\"SelectEmail\",\"\",\"^직접입력\",\"\",\"x\")</script>\r\n");
      out.write("						</select>\r\n");
      out.write("						<div class=\"next-line\">\r\n");
      out.write("							<input type=\"checkbox\" name=\"bMail_rcv\" value=\"1\" onclick=\"$(this).parents('td').find('.alter-notice-wrapper').toggle()\" />\r\n");
      out.write("							할인쿠폰 및 이벤트 정보 수신 (선택)\r\n");
      out.write("							<span class=\"alter-notice-wrapper\">\r\n");
      out.write("								<span class=\"alter-notice pc-text\">이메일/SMS 수신허용 고객님께 신규회원 할인쿠폰이 발급됩니다.</span>\r\n");
      out.write("								<span class=\"alter-notice mobile-text\">수신허용 고객님께 신규회원 할인쿠폰이 발급</span>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>휴대폰번호</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<script language=\"javascript\">make_select_code(\"select\",\"handphone\",\"mobile1\",\"type1 phone1\",\"^선택\",\"\")</script> - \r\n");
      out.write("						<input type=\"text\" name=\"mobile2\" maxlength=\"4\" onkeypress=\"onlyNumber()\" class=\"input1 phone2\" /> - \r\n");
      out.write("						<input type=\"text\" name=\"mobile3\" maxlength=\"4\" onkeypress=\"onlyNumber()\" class=\"input1 phone3\" />\r\n");
      out.write("					\r\n");
      out.write("						<br />\r\n");
      out.write("											\r\n");
      out.write("						\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("						<th>도로명 주소</th>\r\n");
      out.write("					<td>\r\n");
      out.write("					\r\n");
      out.write("						<input type=\"text\" name=\"\" readOnly maxlength=\"10\" class=\"input1\" id=\"sample3_postcode\" />\r\n");
      out.write("						<span class=\"btn-type1 address\"  name=\"address1\" style=\"cursor:pointer\"   onClick=\"sample3_execDaumPostcode()\">우편번호 찾기</span> <br />\r\n");
      out.write("						\r\n");
      out.write("						<input type=\"text\" name=\"address2\" readOnly  class=\"input1\"id=\"sample3_address\" />\r\n");
      out.write("						<input type=\"text\" name=\"address3\" maxlength=\"60\"  class=\"input1\" id=\"sample3_detailAddress\" />\r\n");
      out.write("					</td>\r\n");
      out.write("				\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div id=\"wrap\" style=\"display:none;border:1px solid;width:500px;height:300px;margin:5px 0;position:relative\">\r\n");
      out.write("			<img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\" id=\"btnFoldWrap\" style=\"cursor:pointer;position:absolute;right:0px;top:-1px;z-index:1\" onclick=\"foldDaumPostcode()\" alt=\"접기 버튼\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"contents-wrapper member-info-form\">\r\n");
      out.write("			<h3 class=\"block-title\">부가정보</h3>\r\n");
      out.write("			<table class=\"item-table type1 input-form\">\r\n");
      out.write("				<!-- 결혼기념일 지금은 사용 안함 -->\r\n");
      out.write("                <div style=\"display:none;\"><script language=\"javascript\">fn_ymd(\"Marry\")</script></div>\r\n");
      out.write("			\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th style=\"width:77px;\">첫째</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"field-block\">\r\n");
      out.write("							반려동물 이름\r\n");
      out.write("							<input type=\"text\" name=\"baby1_name\" class=\"input1\" style=\"ime-mode:active; \"/>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"field-block margin-right\">\r\n");
      out.write("							<label><input type=\"radio\" name=\"baby1_sex\" value=\"1\"/> 강아지</label>\r\n");
      out.write("							<label><input type=\"radio\" name=\"baby1_sex\" value=\"2\"/> 고양이</label>\r\n");
      out.write("							<label><input type=\"radio\" name=\"baby1_sex\" value=\"0\"/> 기타</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"field-block\">\r\n");
      out.write("							<span>기념일</span>\r\n");
      out.write("							<script language=\"javascript\">fn_ymd(\"1\")</script>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("			</table>		\r\n");
      out.write("			<p>&nbsp;</p>\r\n");
      out.write("			<table class=\"item-table type1 input-form\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>개인정보 유효기간</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<script>make_select_code(\"checkbox\",\"expireYear\",\"exYear\",\"null\",\"\",\"\",\"nextCodeFnc(this)\",\"chk\",\"\")</script>\r\n");
      out.write("						<span class=\"alter-notice-wrapper\">\r\n");
      out.write("							<span class=\"alter-notice pc-text\">선택하지 않을 경우 관련 법령에 의해 1년 자동 지정</span>\r\n");
      out.write("							<span class=\"alter-notice mobile-text\">선택하지 않을 경우 1년 자동 지정</span>\r\n");
      out.write("						</span>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"action-buttons\">\r\n");
      out.write("				<span class=\"cancel type1\" onClick=\"location.href='/'\" style=\"cursor:pointer;\">취소</span>\r\n");
      out.write("				<span class=\"ok type2\" onClick=\"WriteCheck2();\" style=\"cursor:pointer;\">등록</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 모바일 사이드바 170621-최문영작업 -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // 우편번호 찾기 찾기 화면을 넣을 element\r\n");
      out.write("    var element_wrap = document.getElementById('wrap');\r\n");
      out.write("\r\n");
      out.write("    function foldDaumPostcode() {\r\n");
      out.write("        // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("        element_wrap.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function sample3_execDaumPostcode() {\r\n");
      out.write("        // 현재 scroll 위치를 저장해놓는다.\r\n");
      out.write("        var currentScroll = Math.max(document.body.scrollTop, document.documentElement.scrollTop);\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                \r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                   \r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample3_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample3_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample3_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample3_detailAddress\").focus();\r\n");
      out.write("\r\n");
      out.write("                // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("                // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)\r\n");
      out.write("                element_wrap.style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("                // 우편번호 찾기 화면이 보이기 이전으로 scroll 위치를 되돌린다.\r\n");
      out.write("                document.body.scrollTop = currentScroll;\r\n");
      out.write("            },\r\n");
      out.write("            // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분. iframe을 넣은 element의 높이값을 조정한다.\r\n");
      out.write("            onresize : function(size) {\r\n");
      out.write("                element_wrap.style.height = size.height+'px';\r\n");
      out.write("            },\r\n");
      out.write("            width : '100%',\r\n");
      out.write("            height : '100%'\r\n");
      out.write("        }).embed(element_wrap);\r\n");
      out.write("\r\n");
      out.write("        // iframe을 넣은 element를 보이게 한다.\r\n");
      out.write("        element_wrap.style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" src=\"../resources/js/_vir0001/code.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- AceCounter Log Gathering Script V.7.5.2017020801 -->\r\n");
      out.write("<script language='javascript'>\r\n");
      out.write("	var _AceGID=(function(){var Inf=['gtc14.acecounter.com','8080','AS4A42151972793','AW','0','NaPm,Ncisy','ALL','0']; var _CI=(!_AceGID)?[]:_AceGID.val;var _N=0;var _T=new Image(0,0);if(_CI.join('.').indexOf(Inf[3])<0){ _T.src =( location.protocol==\"https:\"?\"https://\"+Inf[0]:\"http://\"+Inf[0]+\":\"+Inf[1]) +'/?cookie'; _CI.push(Inf);  _N=_CI.length; } return {o: _N,val:_CI}; })();\r\n");
      out.write("	var _AceCounter=(function(){var G=_AceGID;var _sc=document.createElement('script');var _sm=document.getElementsByTagName('script')[0];if(G.o!=0){var _A=G.val[G.o-1];var _G=(_A[0]).substr(0,_A[0].indexOf('.'));var _C=(_A[7]!='0')?(_A[2]):_A[3];var _U=(_A[5]).replace(/\\,/g,'_');_sc.src=(location.protocol.indexOf('http')==0?location.protocol:'http:')+'//cr.acecounter.com/Web/AceCounter_'+_C+'.js?gc='+_A[2]+'&py='+_A[4]+'&gd='+_G+'&gp='+_A[1]+'&up='+_U+'&rd='+(new Date().getTime());_sm.parentNode.insertBefore(_sc,_sm);return _sc.src;}})();\r\n");
      out.write("</script>\r\n");
      out.write("<noscript><img src='http://gtc14.acecounter.com:8080/?uid=AS4A42151972793&je=n&' border='0' width='0' height='0' alt=''></noscript>\r\n");
      out.write("<!-- AceCounter Log Gathering Script End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- WIDERPLANET  SCRIPT START 2018.5.21 (공통) (* 공통 태그는 타 태그(아이템, 장바구니, 구매완료, 전환 완료)보다 하단에 위치하여야 합니다. ) -->\r\n");
      out.write("<div id=\"wp_tg_cts\" style=\"display:none;\"></div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var wptg_tagscript_vars = wptg_tagscript_vars || [];\r\n");
      out.write("wptg_tagscript_vars.push(\r\n");
      out.write("(function() {\r\n");
      out.write("	return {\r\n");
      out.write("		wp_hcuid:\"\",   /*고객넘버 등 Unique ID (ex. 로그인  ID, 고객넘버 등 )를 암호화하여 대입.\r\n");
      out.write("				*주의 : 로그인 하지 않은 사용자는 어떠한 값도 대입하지 않습니다.*/\r\n");
      out.write("		ti:\"41190\",	/*광고주 코드 */\r\n");
      out.write("		ty:\"Home\",	/*트래킹태그 타입 */\r\n");
      out.write("		device:\"web\"	/*디바이스 종류  (web 또는  mobile)*/\r\n");
      out.write("\r\n");
      out.write("	};\r\n");
      out.write("}));\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" async src=\"//cdn-aitg.widerplanet.com/js/wp_astg_4.0.js\"></script>\r\n");
      out.write("<!-- WIDERPLANET  SCRIPT START 2018.5.21 (공통)-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Enliple Common Tracker v3.6 [공용] start -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("function mobRf() {\r\n");
      out.write("    var rf = new EN();\r\n");
      out.write("    rf.setData(\"userid\", \"montraum\");\r\n");
      out.write("    rf.setSSL(true);\r\n");
      out.write("    rf.sendRf();\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Enliple Common Tracker v3.6 [공용] end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.megadata.co.kr/js/en_script/3.6/enliple_min3.6.js\" defer=\"defer\" onload=\"mobRf();\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ADN Tracker[공통] start -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var adn_param = adn_param || [];\r\n");
      out.write("adn_param.push([{ 	\r\n");
      out.write(" ui:'101877',\r\n");
      out.write(" ut:'Home'\r\n");
      out.write("}]);\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" async src=\"//fin.rainbownine.net/js/adn_tags_1.0.0.js\"></script>\r\n");
      out.write("<!-- ADN Tracker[공통] end -->\r\n");
      out.write("\r\n");
      out.write("<!-- ADN 크로징 설치  start -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var adn_panel_param = adn_panel_param || [];\r\n");
      out.write("adn_panel_param.push([{\r\n");
      out.write(" ui:'101877',	\r\n");
      out.write(" ci:'1018770001',\r\n");
      out.write(" gi:'21528'\r\n");
      out.write("}]);\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" async src=\"//fin.rainbownine.net/js/adn_closingad_1.1.1.js\"></script>\r\n");
      out.write("<!-- ADN 크로징 설치 end -->\r\n");
      out.write("\r\n");
      out.write("<!-- ADN 크로징 설치 반응형 start -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var adn_mobile_panel_param = adn_mobile_panel_param || [];\r\n");
      out.write("adn_mobile_panel_param.push([{\r\n");
      out.write(" ui:'101877',  \r\n");
      out.write(" ci:'1018770002',\r\n");
      out.write(" gi:'21530'\r\n");
      out.write("}]);\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" async src=\"//fin.rainbownine.net/js/adn_mobile_closingad_1.1.2.js\"></script>\r\n");
      out.write("<!-- ADN 크로징 설치 end -->\r\n");
      out.write("\r\n");
      out.write("<!-- Google Tag Manager (noscript) -->\r\n");
      out.write("<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-WDLJW3X\"\r\n");
      out.write("		height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\r\n");
      out.write("<!-- End Google Tag Manager (noscript) -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("<!--	\r\n");
      out.write("	form = document.frmReg;\r\n");
      out.write("\r\n");
      out.write("form.Mobile_Ori.value=\"010-1111-1111\"\r\n");
      out.write("form.Email_Ori.value=\"이메일m@naver.com\"\r\n");
      out.write("\r\n");
      out.write("user_name.innerText=\"이름\"\r\n");
      out.write("user_id.innerText=\"이메일\"\r\n");
      out.write("\r\n");
      out.write("form.email.value=\"이메일\"\r\n");
      out.write("form.email2.value=\"naver.com\"\r\n");
      out.write("form.SelectEmail.value=\"naver.com\"\r\n");
      out.write("form.email2.style.backgroundColor = \"#EEEEEE\"\r\n");
      out.write("\r\n");
      out.write("form.zip.value=\"\"\r\n");
      out.write("form.addr1.value=\"\"\r\n");
      out.write("form.addr2.value=\"\"\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	form.road_zip.value = \"\"\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("form.road_addr1.value=\"\"\r\n");
      out.write("form.road_addr2.value=\"\"\r\n");
      out.write("form.tel1.value=\"\"\r\n");
      out.write("form.tel2.value=\"\"\r\n");
      out.write("form.tel3.value=\"\"\r\n");
      out.write("form.mobile1.value=\"010\"\r\n");
      out.write("form.mobile2.value=\"1111\"\r\n");
      out.write("form.mobile3.value=\"1111\"\r\n");
      out.write("check_Rs(form.bMail_rcv,\"0\")\r\n");
      out.write("check_Rs(form.bSMS_rcv,\"0\")\r\n");
      out.write("check_Rs(form.exYear,\"1\");\r\n");
      out.write("\r\n");
      out.write("form.MarryMonth.value=\"\"\r\n");
      out.write("form.MarryDay.value=\"\"\r\n");
      out.write("form.GeekGoon.value=\"0\"\r\n");
      out.write("\r\n");
      out.write("form.baby1_name.value=\"\"\r\n");
      out.write("check_Rs(form.baby1_sex,\"0\")\r\n");
      out.write("form.baby1_birth_1.value=\"\"\r\n");
      out.write("form.baby1_birth_2.value=\"\"\r\n");
      out.write("form.baby1_birth_3.value=\"\"\r\n");
      out.write("\r\n");
      out.write("form.baby2_name.value=\"\"\r\n");
      out.write("check_Rs(form.baby2_sex,\"0\")\r\n");
      out.write("form.baby2_birth_1.value=\"\"\r\n");
      out.write("form.baby2_birth_2.value=\"\"\r\n");
      out.write("form.baby2_birth_3.value=\"\"\r\n");
      out.write("\r\n");
      out.write("form.baby3_name.value=\"\"\r\n");
      out.write("check_Rs(form.baby3_sex,\"0\")\r\n");
      out.write("form.baby3_birth_1.value=\"\"\r\n");
      out.write("form.baby3_birth_2.value=\"\"\r\n");
      out.write("form.baby3_birth_3.value=\"\"\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("$(\".item-table.type1.input-form .btn-type1.address\").click(function(){\r\n");
      out.write("	openPopup(this, \"/common/all_site/zipcode/zipcode_search_step1.asp?s_type=1&p_formname=frmReg&p_zipcode1=zip1&p_old_addr1=addr1&p_old_addr2=addr2&p_new_zip1=n_zip1&p_new_addr1=n_addr1&p_new_addr2=n_addr2\", 550, 900);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\".item-table.type1.input-form .btn-type1.address_new\").click(function(){\r\n");
      out.write("	openPopup(this, \"/common/all_site/zipcode/zipcode_search_step1.asp?s_type=2&p_formname=frmReg&p_zipcode1=zip1&p_old_addr1=addr1&p_old_addr2=addr2&p_new_zip1=n_zip1&p_new_addr1=n_addr1&p_new_addr2=n_addr2\", 550, 900);\r\n");
      out.write("});\r\n");
      out.write("*/\r\n");
      out.write("//우편번호 검색 - 도로명주소 적용\r\n");
      out.write("	function ZipSearch(val) {\r\n");
      out.write("		formname = val;\r\n");
      out.write("		window.open(\"/common/all_site/zipcode/zipcode_2019.asp\",\"zipsearch\",\"width=610,height=660,top=0,left=0, scrollbars=no,resizable\");\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function mobileChk(){\r\n");
      out.write("		\r\n");
      out.write("		if(form.mobile1.value == \"010\" && form.mobile2.value == \"1111\" && form.mobile3.value == \"1111\") {\r\n");
      out.write("			return true;\r\n");
      out.write("		}else{\r\n");
      out.write("			if(form.mobileCert_ok.value == 1){\r\n");
      out.write("				return true;\r\n");
      out.write("			}else{\r\n");
      out.write("				alert(\"휴대폰 인증을 진행해 주십시오\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function certSendSms() {\r\n");
      out.write("		var certNum = \"\";\r\n");
      out.write("		var chars = \"0123456789\";\r\n");
      out.write("		var frm = document.frmReg;\r\n");
      out.write("\r\n");
      out.write("		if (isEmpty(frm.mobile1.value)) {\r\n");
      out.write("			alert(\"핸드폰 번호 앞자리를 선택해 주십시오\");\r\n");
      out.write("			frm.mobile1.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (isEmpty(frm.mobile2.value)) {\r\n");
      out.write("			alert(\"핸드폰 번호 가운데자리를 입력해 주십시오\");\r\n");
      out.write("			frm.mobile2.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (isEmpty(frm.mobile3.value)) {\r\n");
      out.write("			alert(\"핸드폰 번호 뒷자리를 입력해 주십시오\");\r\n");
      out.write("			frm.mobile3.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		for (var i=0; i<6; i++) {\r\n");
      out.write("			var rnum = Math.floor(Math.random() * chars.length);\r\n");
      out.write("			certNum += chars.substring(rnum, rnum + 1);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		frm.certNum.value = certNum;\r\n");
      out.write("\r\n");
      out.write("		frm.action = \"certSendSms.asp\";\r\n");
      out.write("		frm.target = \"hidden_iframe\";\r\n");
      out.write("		frm.submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function certNumCheck() {\r\n");
      out.write("		var frm = document.frmReg;\r\n");
      out.write("\r\n");
      out.write("		if (frm.certNum.value == frm.mobileCertNum.value) {\r\n");
      out.write("			frm.mobileCert_ok.value = 1;\r\n");
      out.write("			alert(\"인증 되었습니다.\");\r\n");
      out.write("		}\r\n");
      out.write("		else {\r\n");
      out.write("			frm.mobileCert_ok.value = \"\";\r\n");
      out.write("			alert(\"인증번호가 틀립니다. 다시 확인해주세요.\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
