/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-11-08 08:08:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div id=\"sitemap\" class=\"only-pc\">\r\n");
      out.write("			<div class=\"pc-width\">\r\n");
      out.write("				<div class=\"inner-div clearfix\">\r\n");
      out.write("					<div class=\"section\">\r\n");
      out.write("						<h3></h3>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section\">\r\n");
      out.write("						<h3>SHOP</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li onclick=\"location.href='shopmain95da.html?iniCategory=24&amp;thisCategory='\"\r\n");
      out.write("								style=\"cursor:pointer;\">사료</li>\r\n");
      out.write("							<li onclick=\"location.href='shopmaind449.html?iniCategory=87&amp;thisCategory='\"\r\n");
      out.write("								style=\"cursor:pointer;\">간식</li>\r\n");
      out.write("							<li onclick=\"location.href='shopmainacb9.html?iniCategory=25&amp;thisCategory='\"\r\n");
      out.write("								style=\"cursor:pointer;\">배변용품</li>\r\n");
      out.write("							<li onclick=\"location.href='shopmain84ed.html?iniCategory=27&amp;thisCategory='\"\r\n");
      out.write("								style=\"cursor:pointer;\">미용</li>\r\n");
      out.write("							<li onclick=\"location.href='shopmaine79f.html?iniCategory=28&amp;thisCategory='\"\r\n");
      out.write("								style=\"cursor:pointer;\">리빙/외출</li>\r\n");
      out.write("							<li onclick=\"location.href='shopmain31f3.html?iniCategory=76&amp;thisCategory='\"\r\n");
      out.write("								style=\"cursor:pointer;\">고양이</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section\">\r\n");
      out.write("						<h3>EVENT</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							\r\n");
      out.write("							<li onclick=\"location.href='event.html'\" style=\"cursor:pointer;\">진행중 EVENT</li>\r\n");
      out.write("							<li onclick=\"location.href='notice-2.html'\" style=\"cursor:pointer;\">당첨자 발표</li>\r\n");
      out.write("							<li onclick=\"location.href='review.html'\" style=\"cursor:pointer;\">BEST REVIEW</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section\">\r\n");
      out.write("						<h3>MEMBER</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li onclick=\"location.href='join_agreement.html'\" style=\"cursor:pointer;\">회원가입</li>\r\n");
      out.write("							<li onclick=\"location.href='login.html'\" style=\"cursor:pointer;\">로그인</li>\r\n");
      out.write("							<li onclick=\"location.href='searchidinfo2ce3.html?ProcessGubun=A'\" style=\"cursor:pointer;\">\r\n");
      out.write("								아이디 찾기</li>\r\n");
      out.write("							<li onclick=\"location.href='searchidinfo0a92.html?ProcessGubun=B'\" style=\"cursor:pointer;\">\r\n");
      out.write("								비밀번호 찾기</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section\">\r\n");
      out.write("						<h3>CONTACT</h3>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li onclick=\"location.href='notice-2.html'\" style=\"cursor:pointer;\">공지사항</li>\r\n");
      out.write("							<li onclick=\"location.href='faq.html'\" style=\"cursor:pointer;\">FAQ</li>\r\n");
      out.write("							<li onclick=\"location.href='list.html'\" style=\"cursor:pointer;\">Q&A</li>\r\n");
      out.write("							<li onclick=\"location.href='aboutus.html'\" style=\"cursor:pointer;\">제휴문의</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!--풋터영역종료-->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
