/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-11-07 02:48:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexReview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"contents-wrapper best-review-wrapper pc-width only-pc\">\r\n");
      out.write("				<div class=\"title-wrapper-title\" style=\"text-align:center; margin-bottom:-30px;  width:100%;\"><img\r\n");
      out.write("						src=\"../resources/images/main_title_04.png\"></div>\r\n");
      out.write("				<div class=\"more-btn\">\r\n");
      out.write("					<img onclick=\"location.href='review9500.html?potoGubun=2'\" style=\"cursor:pointer;\"\r\n");
      out.write("						src=\"../resources/images/bt_more.png\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"mont-review\">\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view5098.html?id=15851'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20211015am83329.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">너무 추천</span><span\r\n");
      out.write("										class=\"id-name\">JIN23*****</span></p>\r\n");
      out.write("								<p class=\"item-description\">두툼하고 흡수도 잘돼서 너무 좋아요!\r\n");
      out.write("									그리고 스티커가 있어서 고정도 잘 됩니다????\r\n");
      out.write("								</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view7759.html?id=15844'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20211012am85146.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">이 사료만 먹여요</span><span\r\n");
      out.write("										class=\"id-name\">LEPEC********</span></p>\r\n");
      out.write("								<p class=\"item-description\">화식으로 바꿔보려고 했는데, 저희 아이는 건사료에 익숙해서 그런지 잘 안 먹더라고요. 그래서 다시 몇년째\r\n");
      out.write("									먹이고 있는 베스트브리드 연어 사료로 돌아왔습니다. 저희 아이는 알러지가 </p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view62c4.html?id=15835'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20211007pm70001.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">세번째구매♡</span><span\r\n");
      out.write("										class=\"id-name\">CLAMP***</span></p>\r\n");
      out.write("								<p class=\"item-description\">세번째 구매네요ㅎㅎ\r\n");
      out.write("									알갱이가 큰편이라 조금 으깨서 주는데\r\n");
      out.write("									강아지가 너무 맛있게 잘먹어요^^</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view4d39.html?id=15823'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210930am102131.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">건강한 사료</span><span\r\n");
      out.write("										class=\"id-name\">JINNY****</span></p>\r\n");
      out.write("								<p class=\"item-description\">울 아이가 잘먹고 건강하게 자라고 있어요.\r\n");
      out.write("									안심하고 먹일수있는 사료를 구할수있어서 얼마나다행인지요! 늘 함께해주길~</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_viewb63e.html?id=15822'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210930am122032.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">3번째 재구매 후기입니당!</span><span\r\n");
      out.write("										class=\"id-name\">YGGH0***</span></p>\r\n");
      out.write("								<p class=\"item-description\">저는 사료 유목민이었어요 ㅠㅠ\r\n");
      out.write("									진짜 2년 동안 계속 바꾸고 처방사료도 먹어봤지만 턱드름이 안 사라졌었어요,,,,,\r\n");
      out.write("									그리고 발가락 사이에 염증이 생기는 지간염도 계속 재발했구</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view6413.html?id=15818'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210924am94129.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">6키로 푸들도 성공 !! ㅠㅠ</span><span\r\n");
      out.write("										class=\"id-name\">HAEUN***</span></p>\r\n");
      out.write("								<p class=\"item-description\">가방 구매는 이번이 처음이라 진짜 많은 제품 알아보고 고르다가 몬트라움 선택했는데 ㅠㅠㅠ\r\n");
      out.write("									사실 구매하면서도 아 들어갈까... 6키로에 푸들인데.... 들어갈까... 엄청 고민하다</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_viewf9d9.html?id=15812'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210916pm93128.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">퍼펙션 패드</span><span\r\n");
      out.write("										class=\"id-name\">K1630*********</span></p>\r\n");
      out.write("								<p class=\"item-description\">사이즈도 적당하고 냄새도 다른 패드보다 덜 나고 흡수력이 정말 짱입니다...색상이 어두워서 노란 오줌이\r\n");
      out.write("									안보이니 미관상 더 나은것 같고..바닥에 부착이 되니 밀리지도 않고 너무 편</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view1225.html?id=15804'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210914pm111041.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">카르나4 울 강쥐가 넘 잘 먹습니다!! </span><span\r\n");
      out.write("										class=\"id-name\">YYSUE*</span></p>\r\n");
      out.write("								<p class=\"item-description\">마약 사료로 불리는 허x사료 이후 이렇게 잘 먹는 건사료는 처음입니다.\r\n");
      out.write("									치킨 거의 다 먹어가서 이번엔 알맹이가 더 작다는 이지츄 두 봉지나 구매했어요.\r\n");
      out.write("									잘 품절된다고 해서 미리</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view43f5.html?id=15786'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210911pm44557.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">왜 카르나 카르나 하는지 알겠어요</span><span\r\n");
      out.write("										class=\"id-name\">ANDMO****</span></p>\r\n");
      out.write("								<p class=\"item-description\">핸드폰 인증번호가 안와서 어렵게 회원가입하고 구매한 카르나4\r\n");
      out.write("									여러 사료를 테스트해보고 결정!\r\n");
      out.write("									급여해보니 변 상태도 좋고 영양소부터 알갱이크기 단단함정도까지 마음에든다\r\n");
      out.write("									꾸</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view448a.html?id=15778'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210908pm11153.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">사료투정하던아이..</span><span\r\n");
      out.write("										class=\"id-name\">IM131*</span></p>\r\n");
      out.write("								<p class=\"item-description\">전자렌지 20초정도 돌려주면\r\n");
      out.write("									아주아주 잘 먹어요\r\n");
      out.write("									응가도 이쁘구????</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_viewec20.html?id=15771'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210903am104600.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">잘 먹어요!!</span><span\r\n");
      out.write("										class=\"id-name\">DLGKS******</span></p>\r\n");
      out.write("								<p class=\"item-description\">오븐이라 그런지 정말 손으로 만졌을따 기름기가 없어요.\r\n");
      out.write("									너무 너무 좋습니다. 사료 냄새는 꼬순내나요.\r\n");
      out.write("									둘째는 처음에는 안먹었고 첫째가 바로 잘 먹었는데 첫째보고는 자기도 따라 </p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view559a.html?id=15767'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210902pm60242.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">꾸준히 사용하는 패드입니다</span><span\r\n");
      out.write("										class=\"id-name\">XQHGH**</span></p>\r\n");
      out.write("								<p class=\"item-description\">다견가정이라 항상 이 패드만 사용해요\r\n");
      out.write("									원래 Xxl 사용하다가 xl도 한번 사봤어요\r\n");
      out.write("									쉬아 색이 안보여서 좋아요 흡수력도 최고입니당</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view63a3.html?id=15765'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210901am74746.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">역시..!! 좋네요</span><span\r\n");
      out.write("										class=\"id-name\">OUTOF*******</span></p>\r\n");
      out.write("								<p class=\"item-description\">푸들 전용과 독 다이어트 번갈아 먹이고 있어요. 이번엔 두 팩으로 사료창고를 채웠어요.</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view6242.html?id=15764'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210831pm21211.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">2년째 먹이는 사료입니다</span><span\r\n");
      out.write("										class=\"id-name\">LEPEC********</span></p>\r\n");
      out.write("								<p class=\"item-description\">육류 알러지에 아마씨 알러지까지 있는 아이를 키우고 있어 먹일 수 있는 사료가 많지 않습니다.다행히\r\n");
      out.write("									베스트브리드 홀리스틱 콜드 워터 레시피 연어는 육류, 아마씨가 함유 되지 않아 </p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view278b.html?id=15755'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210824am93127.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">침대를 너무 좋아해요</span><span\r\n");
      out.write("										class=\"id-name\">N1628*********</span></p>\r\n");
      out.write("								<p class=\"item-description\">오랜만에 침대를 바꿔줬는데, 바로 적응하고 저렇게 꿀잠을 자네요.5kg 미니어처푸들인데 튼튼하고 크기도\r\n");
      out.write("									적당해 만족합니다.&nbsp;</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view56e5.html?id=15750'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210823pm12239.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">잘 먹어요!! 감동ㅠㅠ</span><span\r\n");
      out.write("										class=\"id-name\">YYSUE*</span></p>\r\n");
      out.write("								<p class=\"item-description\">울 강쥐 이제 겨우 1살인데,\r\n");
      out.write("									심한 편식견이에요ㅠㅠ\r\n");
      out.write("									마약사료도 거부, 동결건조, 화식도 거부ㅠㅠ\r\n");
      out.write("									멍생보감에 성분 좋은 사료 검색하고,\r\n");
      out.write("									강사모에서도 검색하고,\r\n");
      out.write("									네이버 쇼핑에</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_viewa044.html?id=15745'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210821pm51921.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">완전 좋아요</span><span\r\n");
      out.write("										class=\"id-name\">TNGKS****</span></p>\r\n");
      out.write("								<p class=\"item-description\">우리집 강아지가 너무 좋아하네요밥먹는거 아니면 계속 올라가있어요엄청 편안해 보여서 저도 누워보니,\r\n");
      out.write("									푹신푹신한게 좋네요그리고 강아지가 방석위에 쉬를 했는데 방수가 되더라구요?!좋은 </p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_view24e0.html?id=15741'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210817am103256.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">너무 잘먹어요^^</span><span\r\n");
      out.write("										class=\"id-name\">CLAMP***</span></p>\r\n");
      out.write("								<p class=\"item-description\">항상 알갱이가 작은사료만 사서 먹였는데 강아지가 급하게 먹구 삼키면서 켁켁되는게 너무 심해서 큰알갱이사료를\r\n");
      out.write("									찾게 되었네요\r\n");
      out.write("									성분도 좋아야해서 고르다가 카르나4를 선택하게 되었어요^</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"page-block\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_viewe70a.html?id=15722'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210804pm50058.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">최고최고</span><span class=\"id-name\">HOYEE*</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"item-description\">-견종 : 킹찰스 스파니엘\r\n");
      out.write("									-몸무게 : 5.7kg\r\n");
      out.write("									-체고: 35cm\r\n");
      out.write("									-몸길이(머리~엉덩이) : 55cm\r\n");
      out.write("									-앉은키 : 40cm\r\n");
      out.write("\r\n");
      out.write("									조만간 기차로 장거리 이동을 해야해서 이</p>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"item\" onclick=\"location.href='review_viewb7ab.html?id=15719'\"\r\n");
      out.write("								style=\"cursor:pointer;\">\r\n");
      out.write("								<div\r\n");
      out.write("									style=\"width:236px;height:186px;background-position:center center;background-repeat:no-repeat;background-size:236px 186px;text-align:center;background-image:url(../resources/images/20210803pm90101.jpg);\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"item-title\"><span class=\"title\">너무너무 잘먹어요^^</span><span\r\n");
      out.write("										class=\"id-name\">EKDMS****</span></p>\r\n");
      out.write("								<p class=\"item-description\">저희 애기들이 엄청잘먹아요! 구토증상없이 식감이 바삭바삭한지 저희집 사료종류다 여섯개 인데 카리나 4 가\r\n");
      out.write("									압도적이네요 강아지꺼도 삿는다 다잘먹어요 이제부터 정착입니다 ??</p>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<script>\r\n");
      out.write("				$('#mont-review').owlCarousel({\r\n");
      out.write("					loop: false,\r\n");
      out.write("					items: 2,\r\n");
      out.write("					margin: 0,\r\n");
      out.write("					nav: true,\r\n");
      out.write("					dots: false,\r\n");
      out.write("					dotsEach: 2,\r\n");
      out.write("					navText: ['<img src=\"../resources/images/btn_prevw.png\">', '<img src=\"../resources/images/btn_next-2.png\">'],\r\n");
      out.write("					responsive: {\r\n");
      out.write("						360: { margin: 0 },\r\n");
      out.write("						1000: { margin: 20 }\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("			</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<style type=\"text/css\">\r\n");
      out.write("				.wide_twobanner07 {\r\n");
      out.write("					background-image: url(\"../resources/images/main_wide_banner_18_bg.jpg\");\r\n");
      out.write("					background-repeat: repeat;\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				.wide_twobanner07 .contents-wrapper {\r\n");
      out.write("					width: 1120px;\r\n");
      out.write("					margin: 0 auto;\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				.wide_twobanner07 .contents-wrapper a {\r\n");
      out.write("					overflow: hidden;\r\n");
      out.write("				}\r\n");
      out.write("			</style>\r\n");
      out.write("\r\n");
      out.write("			<section>\r\n");
      out.write("				<div class=\"wide_twobanner07\">\r\n");
      out.write("					<div class=\"contents-wrapper only-pc\">\r\n");
      out.write("						<a href=\"eventviewfdd5.html?idx=350\">\r\n");
      out.write("							<img src=\"../resources/images/main_wide_banner_18.jpg\" alt=\"첫구매특가\" title=\"첫구매특가\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
